# Generated by Django 2.2 on 2019-11-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191121_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='items/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='items/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='items/%Y/%m/%d/'),
        ),
    ]
