# Generated by Django 2.2 on 2019-12-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191230_0527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentc',
            options={'verbose_name_plural': 'PaymentsC'},
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('sm', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large'), ('xxl', 'extra extra large')], default=39, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wholesaler',
            name='size',
            field=models.CharField(choices=[('sm', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large'), ('xxl', 'extra extra large')], default=39, max_length=2),
            preserve_default=False,
        ),
    ]
