# Generated by Django 2.2 on 2019-12-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191231_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('sm', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large'), ('xxl', 'extra extra large')], default=39, max_length=2),
            preserve_default=False,
        ),
    ]
